[package]
name = "pxls"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
image = "0.25.5"
indicatif = "0.17.9"

# [profile.release]
# debug = true
